import { Manrope,} from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";
import Footer from "@/components/Footer/Footer";
import { ToastContainer } from "react-toastify";

const manRope = Manrope({
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${manRope.className} h-full antialiased`}
    >
      <body className="bg-[#F1F5F9]">
        <Navbar></Navbar>
        {children}
        <Footer></Footer>
        <ToastContainer />
      </body>
    </html>
  );
}
